"""汇总 factor DolphinDB 模块需要编译的函数。"""

from .preprocess import FACTOR_FILTER_NULLS, FACTOR_PREPROCESS
from .statistics import (
    FACTOR_EXECUTION_STATISTICS,
    FACTOR_GROUP_RETURNS,
    FACTOR_GROUP_TURNOVER,
    FACTOR_INFORMATION_COEFFICIENT,
)

FACTOR_FUNCTIONS = (
    FACTOR_FILTER_NULLS,
    FACTOR_PREPROCESS,
    FACTOR_EXECUTION_STATISTICS,
    FACTOR_INFORMATION_COEFFICIENT,
    FACTOR_GROUP_RETURNS,
    FACTOR_GROUP_TURNOVER,
)

__all__ = ["FACTOR_FUNCTIONS"]

