"""导出 backtest DolphinDB 模块函数。"""

from .build_backtest_message import BUILD_BACKTEST_MESSAGE
from .calendar import (
    GET_TRADING_DAYS,
    IS_TRADING_DAY,
    NEXT_TRADING_DAY,
    PREVIOUS_TRADING_DAY,
    SHIFT_TRADING_DAY,
)
from .data import (
    CAN_TRADE,
    CURRENT_SNAPSHOT,
    GET_HISTORY_DATA,
    GET_LAST_DATA,
    HISTORY,
)
from .orders import (
    ORDER_TARGET,
    ORDER_TARGET_PERCENT,
    ORDER_TARGET_PORTFOLIO,
    ORDER_TARGET_VALUE,
)
from .params import GET_PARAMS
from .portfolio import (
    GET_AVAILABLE_CASH,
    GET_OPEN_ORDERS,
    GET_PORTFOLIO,
    GET_POSITION,
    GET_POSITIONS,
    GET_TOTAL_EQUITY,
)
from .return_summary import STANDARDIZE_RETURN_SUMMARY
from .run_backtest import RUN_BACKTEST
from .scheduler import RUN_DAILY, RUN_MONTHLY, RUN_WEEKLY

BACKTEST_FUNCTIONS = (
    GET_PARAMS,
    GET_TRADING_DAYS,
    IS_TRADING_DAY,
    SHIFT_TRADING_DAY,
    PREVIOUS_TRADING_DAY,
    NEXT_TRADING_DAY,
    GET_HISTORY_DATA,
    GET_LAST_DATA,
    HISTORY,
    CURRENT_SNAPSHOT,
    CAN_TRADE,
    GET_PORTFOLIO,
    GET_TOTAL_EQUITY,
    GET_POSITIONS,
    GET_POSITION,
    GET_AVAILABLE_CASH,
    GET_OPEN_ORDERS,
    ORDER_TARGET,
    ORDER_TARGET_VALUE,
    ORDER_TARGET_PERCENT,
    ORDER_TARGET_PORTFOLIO,
    RUN_DAILY,
    RUN_WEEKLY,
    RUN_MONTHLY,
    BUILD_BACKTEST_MESSAGE,
    RUN_BACKTEST,
    STANDARDIZE_RETURN_SUMMARY,
)
